//Assignment Code
var generateBtn = document.querySelector("#generate");

// Add event listener to generate button
generateBtn.addEventListener("click", passwordGenerator);
// all characters that will be allowed in password should the user want
let pwingredients= {
  lowercase: 'abcdefghijklmnopqrstuvwxyz',
  uppercase: 'ABCDEFGHIJKLMNOPQRSTUVWXYZ',
  number: '0123456789',
  symbol: "!\"#$%&'()*+,-./:;<=>?@[\\]^_`{|}~",
};
// main function that will generate the password
function passwordGenerator() {
  var pwcharacterslength = "";
//will accept the input length as generated by the user
  var length = window.prompt("Your password length can be between 8 and 128 characters.  Input your desired length in that range now please!");
//will allow lowercase if confirmed, won't allow if cancel is clicked
  var lowercase = window.confirm("Would you like to use lowercase letters?");
      if (lowercase) {
   pwcharacterslength  += pwingredients.lowercase;
  };
//will allow uppercase if confirmed, won't allow if cancel is clicked
  var uppercase = window.confirm("Would you like to use uppercase letters?");
      if (uppercase) {
    pwcharacterslength += pwingredients.uppercase;
  };
//will allow symbols if confirmed, won't allow if cancel is clicked
  var symbols = window.confirm("Would you like to use symbols?");
      if (symbols) {
    pwcharacterslength += pwingredients.symbol;
  };
//will allow numbers if confirmed, won't allow if cancel is clicked
var numbers = window.confirm("Would you like to use numbers?");
      if (numbers) {
    pwcharacterslength += pwingredients.number;
  };
//set variable to store the password after for statement is run
  var password ="";
  for (let i = 0; i < length; i++) {
    password += pwcharacterslength  [Math.floor(Math.random()* (pwcharacterslength.length))]
//display password to box on the browser
  document.getElementById("password").innerHTML = password;
  }}